// Upstream shipped only "ping" here and hand-wrote the remaining permissions into
// permissions/autogenerated/commands/google-admob.toml (despite its "DO NOT EDIT" header). We
// list every command instead so tauri-plugin generates all allow-*/deny-* permissions itself —
// that keeps permissions/ honest and means adding a command is a one-line change here.
const COMMANDS: &[&str] = &[
    "ping",
    "initialize",
    "request_consent",
    "get_consent_status",
    "show_privacy_options_form",
    "show_banner",
    "hide_banner",
    "prepare_interstitial",
    "show_interstitial",
    "prepare_rewarded",
    "show_rewarded",
    "prepare_rewarded_interstitial",
    "show_rewarded_interstitial",
    "prepare_app_open",
    "show_app_open",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
